### ISSUE TITLE
Getting web3.exceptions.BadFunctionCallOutput on simple function call

### ISSUE THREAD

**Issue by rotarui** [pipermerriam/web3.py#176]
* Version: 3.8.0
* Python: 2.7
* OS: linux

### What was wrong?
I have a very simple contract in which I store a struct map
```
contract      A
{
    struct B
    {
        bool      set;
    }

    mapping (uint56 => B)   myMap;

    function isIn(uint56 _id) constant returns (bool)
    {
        return (myMap[_id].set);
    }
}
```
In another contract, I have an array of A contracts
```  
  function isIn(uint56 _id) constant returns (bool)
    {
        uint  i = 0;
        while (arrayOfContractA[i] != 0)
            {
                if (A(arrayOfContractA[i]).isIn(_id))
                    return (true);
                i += 1;
            }
            return (false);
    }
```
When testing with truffle console, I'm getting normal return values like `true` of `false`.
When I call the second `isIn` method from web3.py and I enter and `_id` that is registered, everything works well and I get `True` returned.
But when I ask for an `_id` I didn't registered, I get this : 
```
web3.exceptions.BadFunctionCallOutput: Could not decode contract function call isIn return data 0x for output_types [u'bool']
```
I don't understand how It could send someting different on false ?!
Why do I have `true` and `false` in truffle (so web3.js), but not in web.py ?
Is `0x` returned when trying to return an uninitialised entry of a map ?
I compiled my contract with solidity 0.4.4

Did this in web3.py
```
self._compiled = solc.compile_files([contractDir + "/A.sol", contractDir + "/B.sol", contractDir + "/B.sol"])
self._coreKey = contractDir + "/A.sol:A"
[...]
self._Core = self._web3.eth.contract(
                            abi=self._compiled[str(self._coreKey)]['abi'],
                            bytecode=self._compiled[str(self._coreKey)]['bin'],
                            bytecode_runtime=self._compiled[str(self._coreKey)]['bin-runtime'],
                            address=self._address)
[...]
self._Core.call().isIn(123)
```
and It crashes on the last line :/

Thanks !

**Comment by pipermerriam** [comment]
Do I understand correctly that `web3.js` correctly returns `false`?

**Comment by rotarui** [comment]
Yes, 
but I use `web3.js` only for Truffle and for pure contract development.

**Comment by rotarui** [comment]
I am actually trying to deploy from `web3.py` and not from `web3.js` and see if the same happens.
I'll do it tonight, I'll come back as soon as I finished.

**Comment by pipermerriam** [comment]
It sounds like `web3.js` is being more forgiving of EVM return values than `web3.py`.  The return value that you are getting, `0x` is indicative of no return value.  False should be returned as `0x0000....`.  Normally, when this error occurs it is because someone is trying to interact with a contract that does not exist.  Can you verify the following things for me as I'm curious if this has anything to do with your version of solc which is a bit dated.

1. See if you can return `false` in any way and have it be correctly interpreted.
2. In your function with the while loop, what happens when you hard code a `return false` at the beginning of that function body?
3. Double check that there is in-fact bytecode located at the address of the contract you are interacting with.

**Comment by rotarui** [comment]
Ok so I just added a `return (false)` at the beginning of my function and It's working.
I was doing something wrong by iterating through an array, uninitialised values inside it aren't initialised to 0 as a map, my bad !
Now I have another problem where any method call that requires a transaction isn't doing anything and I get no errors. Any hints on that ? :/

**Comment by rotarui** [comment]
Ok so I had to use `transact` instead of `call`, my bad again !
