### ISSUE TITLE
Transaction dict key for data differs between getTransaction() and sendTransaction()

### ISSUE THREAD

**Issue by veox** [pipermerriam/web3.py#184]
* Version: 3.8.1
* Python: 3.5
* OS: Ubuntu 16.04.2 LTS

### What seems wrong?

When getting a transaction that has data attached with `tx = web3.eth.getTransaction(txhash)`, the data will be accessible via `tx['input']`.

When sending a transaction with data, the expected key for data is `data`.

So, to re-send the same transaction with an increased gas price, something like the following has to be done (in REPL):

``` python
tx = web3.eth.getTransaction(txhash)
tx['gasPrice'] = int(tx['gasPrice'] * 1.11)
tx['data'] = tx['input'] # <--------------- somewhat unexpected
web3.eth.sendTransaction(tx)
```

Otherwise, the transaction will have been re-created without data at all.

Many of the other keys are quite similar - is there a reason for this "mismatch"?

### A solemn monkey

Source: [/u/squamuglia @ /r/aww](https://www.reddit.com/r/aww/comments/2utmsk/rare_aww_a_golden_snubnosed_monkey_from_the/)

![Tiny snub-nosed monkey sitting on a branch of a tree](https://i.imgur.com/cS1ERzK.jpg)

**Comment by carver** [comment]
Note that this same problem exists directly in `geth attach`, so this would be papering over geth's issue. I haven't tested if it also happens in parity, etc.

**Comment by veox** [comment]
Ah!

@pipermerriam: If this should be taken upstream, perhaps you know where "upstream" is? `go-ethereum`? Both that and `parity`? The `EIP` community?..

**Comment by pipermerriam** [comment]
Yes, I would consider this an upstream bug as both of these methods conform to the JSON-RPC spec.

**Comment by pipermerriam** [comment]
It's not a trivial EIP to create, but having a formal agreed upon RPC spec that the clients could test against would be really powerful.  I know @flyswatter (Dan Finlay) was working on something like this at one point but I don't know what the progress was.

**Comment by flyswatter** [comment]
You refer to [EipSignal](https://github.com/MetaMask/IPFS-Ethereum-Hackathon/issues/14), which proposes using a DAO to manage a [public compatibility table](http://cdetr.io/eth-compat-table/) whose test spec format is up for discussion in [eip 217](https://github.com/ethereum/EIPs/issues/217).

I largely passed off the creation of that DAO to the Boardroom team for the moment, because they had some of the required pieces in place, but will hopefully have some fresh time to get back on that soon, because I see a lot of these incompatibilities popping up.
