### ISSUE TITLE
Switch to `ctoolz library

### ISSUE THREAD

**Issue by pipermerriam** [pipermerriam/web3.py#213]
### What was wrong?

The `toolz` library is pretty awesome, but it is all pure python and thus, as slow as other pure python *stuff*.

Turns out there is a c implementation of the entire library!  https://pypi.python.org/pypi/cytoolz

### How can it be fixed?

Change to use [`ctoolz`](https://pypi.python.org/pypi/cytoolz)

**Comment by djrtwo** [comment]
Did the migration. Everything works fine except when calling `pytest` in `conftest.py` where `functools.wrap` is expecting `cytoolz.functoolz.Compose` to have `__module__` defined but it does not. Using `toolz.compose` rather than `cytoolz.compose` in this one instance is a decent work around if we want to get this merged right now. 

I've opened up an [issue](https://github.com/pytoolz/cytoolz/issues/103) with cytoolz and looking for guidance on resolving it from them.

Let me know if you want the almost complete Pull Request or if you want me to see what cytoolz says first.

Stack trace when calling `pytest` for reference:
![screen shot 2017-08-07 at 6 23 32 pm](https://user-images.githubusercontent.com/1433595/29049765-924efb76-7b9d-11e7-9388-f2b37669c19d.jpg)

**Comment by pipermerriam** [comment]
Can you do this as a local work-around.

```python
from cytoolz import (
    compose as _compose
)

def compose(*args, **kwargs):
    # workaround for https://github.com/pytoolz/cytoolz/issues/103
    return _compose(*args, **kwargs)
```

Easy workaround.  Thanks for doing this.

**Comment by djrtwo** [comment]
Turns out the actual `Compose` class needs __module__ defined. Tried to import it and just monkey patch it but can't because it's compiled c-code.
```python
from cytoolz import (
    Compose
)

Compose.__module__ = "cytoolz.functoolz"
```
error:
> TypeError: can't set attributes of built-in/extension type 'cytoolz.functoolz.Compose'

Dug around but not sure best way to proceed. Any other proposed workaround?

**Comment by pipermerriam** [comment]
pull the implementation that currently lives in the `ethereum-utils` library and vendor it into this codebase with a link to the offending issue in the `cytoolz` repo so that we know where to check if the issue is fixed, then we can remove the local implementation.

**Comment by pipermerriam** [comment]
https://github.com/pipermerriam/ethereum-utils

**Comment by djrtwo** [comment]
@pipermerriam the very function I removed a couple of weeks ago! PR coming

**Comment by pipermerriam** [comment]
:P  thanks for your persistence on this not-so trivial complication.

**Comment by djrtwo** [comment]
ready to close
