### ISSUE TITLE
Is it possible deploy contract,send transaction, using rawprivatekey?

### ISSUE THREAD

**Issue by SlavikDMI** [pipermerriam/web3.py#432]
I have private key without password. It isn't encoded.
Is it possible to sign transaction and **deploy contracts**?

**Comment by carver** [comment]
> Is it possible to sign transaction...

Yes, in the v4 beta. See signTransaction docs here: http://web3py.readthedocs.io/en/latest/web3.eth.account.html#web3.eth.account.Account.signTransaction

> ...  and deploy contracts?

Not in a one-liner. One option would be to write a middleware that intercepts any `eth_sendTransaction` request and signs it using signTransaction instead of letting the provider call the client. Middleware docs here: http://web3py.readthedocs.io/en/latest/internals.html#middlewares

The best solution will probably be #430 . If you're interested in contributing to web3.py, we would definitely welcome it. There's even a bounty on that issue.

**Comment by carver** [comment]
Please reopen if more clarification is needed.
